# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'NoName' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoName
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'R.swift'
	pod 'Blueprints'
	pod 'Alamofire'
	pod 'SnapKit' 
  pod 'NVActivityIndicatorView'
  pod 'Cache'

  target 'NoNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoNameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
